### ISSUE TITLE
[NumericInput] Click on controls results in wrong value

### ISSUE THREAD

**Issue by kamilmateusiak** [livechat/design-system#302] opened 2022-03-13 20:31 UTC
Hello. I noticed that controls of NumericInput are not handled properly. When clicking multiple times something strange is happening with input state and the value is not correct. 

![numeric-input-issue](https://user-images.githubusercontent.com/24607370/158077897-2f497f89-7fac-4f32-8409-cefcb28be5d0.gif)

Steps to reproduce: 
- visit basic story of numeric input 
- click multiple (at least 3) times on up control of numeric input

**Comment by skrabkab-design** [comment] 2022-03-14 11:45
Thanks for reporting @kamilmateusiak ! 🙌

@marcinsawicki Can you please take a look?

**Comment by marcinsawicki** [comment] 2022-07-26 12:59
I can't reproduce this problem

**Comment by sgraczyk** [comment] 2022-07-26 13:19
I'm also unable to reproduce. Closing.

**Closed by sgraczyk** 2022-07-26 13:19 UTC
Labels: bug
